/// Environment configuration for API endpoints and keys.
class AppConfig {
  AppConfig._();

  // ─── API Base URL ──────────────────────────────────────
  // TODO: Replace with your Render backend URL for production
  static const String apiBaseUrl = 'http://localhost:3000/api/v1';
  static const String productionApiUrl = 'https://your-app.onrender.com/api/v1';

  // ─── Firebase ──────────────────────────────────────────
  // Configured via firebase_options.dart (generated by FlutterFire CLI)

  // ─── Razorpay ──────────────────────────────────────────
  // TODO: Replace with live key before production
  static const String razorpayKeyId = 'rzp_test_XXXXXXXXXX';

  // ─── Cloudinary ────────────────────────────────────────
  static const String cloudinaryCloudName = 'your-cloud-name';
  static const String cloudinaryUploadPreset = 'hopo_uploads';

  // ─── App Constants ─────────────────────────────────────
  static const String appName = 'HOPO SHOP';
  static const String appTagline = 'Premium Women\'s Fashion';
  static const String currency = '₹';
  static const String currencyCode = 'INR';
  static const int otpLength = 6;
  static const int otpTimeoutSeconds = 60;

  // ─── Pagination ────────────────────────────────────────
  static const int defaultPageSize = 20;

  // ─── Timeouts ──────────────────────────────────────────
  static const Duration connectTimeout = Duration(seconds: 15);
  static const Duration receiveTimeout = Duration(seconds: 15);
}
