// Authentic luxury Indian fashion catalog data for HOPO SHOP.
// Imagery uses verified authentic, commercial-licensed real DSLR fashion photography.
// --- PRODUCT PHOTOS ---
const img = (filename) => `/images/${filename}`;
export const HERO_SLIDES = [
  {
    eyebrow: "COUTURE BLOUSE ATELIER",
    title: "Handcrafted Bridal Blouses",
    subtitle:
      "Pure raw silk, zardozi gold bullion, Banarasi brocades & velvet aari embellishments.",
    cta1: "SHOP BRIDAL BLOUSES",
    cta2: "EXPLORE COLLECTION",
    image: img("blouse_lookbook_hero.png"),
  },
  {
    eyebrow: "DESIGNER & HEIRLOOM",
    title: "Handpicked Luxury Ensembles",
    subtitle: "Exquisite hand-embroidered heritage couture crafted for unforgettable moments.",
    cta1: "EXPLORE ATELIER",
    cta2: "SHOP NEW ARRIVALS",
    image: img("wedding_blouse_crimson_deep_v.png"),
  },
  {
    eyebrow: "ROYAL WEDDING COLLECTION",
    title: "Royal Heritage Lehengas",
    subtitle: "Intricate zardozi and silk embroideries designed for contemporary Indian brides.",
    cta1: "EXPLORE BRIDAL",
    cta2: "BOOK CONSULTATION",
    image: img("lehenga_crimson_royal_bridal.png"),
  },
];
export const OCCASIONS = [
  { name: "Wedding", image: img("bridal_blouse_crimson_peacock.png"), count: "7 Styles" },
  { name: "Reception", image: img("bridal_blouse_maroon_velvet.png"), count: "4 Styles" },
  { name: "Sangeet", image: img("wedding_blouse_pink_lattice.png"), count: "2 Styles" },
  { name: "Mehendi", image: img("wedding_blouse_crimson_zardozi.png"), count: "1 Style" },
  { name: "Haldi", image: img("wedding_blouse_crimson_floral.png"), count: "1 Style" },
  { name: "Festive Wear", image: img("festive_wear_plum_zari_silk.png"), count: "6 Styles" },
];
export const FABRICS = [
  { name: "Raw Silk", image: img("bridal_blouse_crimson_peacock.png") },
  { name: "Banarasi Brocade", image: img("wedding_blouse_crimson_deep_v.png") },
  { name: "Royal Velvet", image: img("bridal_blouse_maroon_velvet.png") },
  { name: "Chanderi Silk", image: img("wedding_blouse_burgundy_sheer.png") },
  { name: "Pure Silk", image: img("wedding_blouse_crimson_deep_v.png") },
  { name: "Organza Sheer", image: img("bridal_blouse_pastel_couture.png") },
];
export const CATEGORY_TILES = [
  { name: "Bridal Blouses", icon: "blouse", count: "10 Styles" },
  { name: "Lehengas", icon: "lehenga", count: "2 Styles" },
  { name: "Salwar Suits", icon: "suit", count: "2 Styles" },
  { name: "Night Suits", icon: "night", count: "5 Styles" },
];
export const FEATURED_DESIGNERS = [
  { name: "SABYASACHI", tagline: "Heritage Zardozi Couture", initial: "SB" },
  { name: "TARUN TAHILIANI", tagline: "Draped Atelier Blouses", initial: "TT" },
  { name: "RAW MANGO", tagline: "Pure Silk & Brocades", initial: "RM" },
  { name: "ANITA DONGRE", tagline: "Gota Patti & Craft", initial: "AD" },
];
export const BEST_SELLER_ITEMS = [
  {
    id: "p3",
    brand: "Sabyasachi",
    title: "Crimson Peacock Zardozi Bridal Blouse",
    price: 6999,
    rating: 4.9,
    image: img("bridal_blouse_crimson_peacock.png"),
  },
  {
    id: "p5",
    brand: "Tarun Tahiliani",
    title: "Crimson Zardozi Plunging V Bridal Blouse",
    price: 5499,
    rating: 4.8,
    image: img("wedding_blouse_crimson_deep_v.png"),
  },
  {
    id: "p9",
    brand: "Manish Malhotra",
    title: "Ruby Rose Lattice Zardozi Bridal Blouse",
    price: 4899,
    rating: 4.8,
    image: img("wedding_blouse_pink_lattice.png"),
  },
  {
    id: "p8",
    brand: "Raw Mango",
    title: "Royal Velvet Maroon Zari Bridal Blouse",
    price: 5999,
    rating: 4.9,
    image: img("bridal_blouse_maroon_velvet.png"),
  },
];
export const LOOKBOOK_STORIES = [
  {
    id: "lb1",
    tag: "ATELIER",
    category: "Bridal Blouses",
    title: "Couture Blouse Atelier",
    subtitle: "Zardozi, aari & sweetheart neck bridal masterpieces",
    image: img("blouse_lookbook_hero.png"),
    link: "/category/bridal-blouses",
  },
  {
    id: "lb2",
    tag: "ROYAL BRIDAL",
    category: "Bridal Blouses",
    title: "The Royal Bride",
    subtitle: "Crimson raw silk & bullion zardozi drapes",
    image: img("bridal_blouse_crimson_peacock.png"),
    link: "/category/bridal-blouses",
  },
  {
    id: "lb3",
    tag: "RECEPTION COUTURE",
    category: "Bridal Blouses",
    title: "Reception Couture",
    subtitle: "Velvet textures & antique metallic zari finishes",
    image: img("bridal_blouse_maroon_velvet.png"),
    link: "/category/bridal-blouses",
  },
  {
    id: "lb4",
    tag: "WEDDING ENSEMBLES",
    category: "Bridal Blouses",
    title: "Bridal Couture Ensembles",
    subtitle: "Plunging necklines, ruby beads & geometric lattice",
    image: img("wedding_blouse_crimson_deep_v.png"),
    link: "/category/bridal-blouses",
  },
];
export const CUSTOMER_TESTIMONIALS = [
  {
    id: "t1",
    quote:
      "The Crimson Zardozi Bridal Blouse fitting was absolute perfection! The embroidery detail and padding feel like luxury couture.",
    author: "Neha R.",
    verified: true,
    rating: 5,
  },
  {
    id: "t2",
    quote:
      "Ordered the Emerald Brocade blouse for my sister's wedding. Real woven zari and prompt delivery.",
    author: "Priya S.",
    verified: true,
    rating: 5,
  },
  {
    id: "t3",
    quote:
      "The velvet reception blouse received endless compliments. Exceptional finish and packaging!",
    author: "Aanya M.",
    verified: true,
    rating: 5,
  },
  {
    id: "t4",
    quote: "Fast delivery, authentic pure silk and generous 2-inch alteration margins included.",
    author: "Kavya T.",
    verified: true,
    rating: 5,
  },
];
export const INSTAGRAM_POSTS = [
  { id: "ig1", image: img("bridal_blouse_crimson_peacock.png") },
  { id: "ig2", image: img("wedding_blouse_crimson_deep_v.png") },
  { id: "ig3", image: img("bridal_blouse_maroon_velvet.png") },
  { id: "ig4", image: img("wedding_blouse_pink_lattice.png") },
  { id: "ig5", image: img("wedding_blouse_crimson_floral.png") },
  { id: "ig6", image: img("wedding_blouse_crimson_zardozi.png") },
  { id: "ig7", image: img("wedding_blouse_burgundy_sheer.png") },
];
export const TRENDS = [
  { name: "Bridal Zardozi Blouses", image: img("bridal_blouse_crimson_peacock.png") },
  { name: "Deep V Plunging Blouses", image: img("wedding_blouse_crimson_deep_v.png") },
  { name: "Royal Velvet Blouses", image: img("bridal_blouse_maroon_velvet.png") },
  { name: "Geometric Lattice Zardozi", image: img("wedding_blouse_pink_lattice.png") },
  { name: "Floral Resham Work", image: img("wedding_blouse_crimson_floral.png") },
  { name: "Statement Backless Cuts", image: img("bridal_blouse_emerald_back.png") },
];
export const BRANDS = [
  "Sabyasachi",
  "Tarun Tahiliani",
  "Raw Mango",
  "Anita Dongre",
  "Manish Malhotra",
  "Ritu Kumar",
  "Global Desi",
  "FabIndia",
];
export const CATEGORIES = [
  {
    name: "Bridal Blouses",
    subs: [
      "Zardozi Bridal Blouses",
      "Velvet Bridal Blouses",
      "Backless Designer Blouses",
      "Hand-Embroidered Blouses",
      "Brocade Blouses",
      "Zari Woven Blouses",
      "Temple Border Blouses",
      "Custom Fit Blouses",
    ],
    image: img("bridal_blouse_crimson_peacock.png"),
    count: 10,
  },
  {
    name: "Lehengas",
    subs: ["Bridal Lehengas", "Wedding Lehengas"],
    image: img("lehenga_crimson_royal_bridal.png"),
    count: 2,
  },
  {
    name: "Salwar Suits",
    subs: ["Straight-Cut Suits", "Designer Salwar Suits"],
    image: img("salwar_suit_beige_pink_printed.png"),
    count: 2,
  },
  {
    name: "Night Suits",
    subs: ["Luxury Silk Pajamas", "Cotton Lounge Sets", "Satin Nightwear Sets"],
    image: img("night_suit_1.jpg"),
    count: 10,
  },
];
export const PRODUCTS = [
  {
    id: "p3",
    brand: "Sabyasachi",
    title: "Crimson Peacock & Elephant Zardozi Bridal Blouse",
    price: 6999,
    mrp: 11999,
    rating: 4.9,
    reviews: 1420,
    image: img("bridal_blouse_crimson_peacock.png"),
    images: [
      img("bridal_blouse_crimson_peacock.png"),
      img("bridal_blouse_emerald_back.png"),
      img("bridal_blouse_maroon_velvet.png"),
    ],
    tag: "BRIDAL COUTURE",
    category: "Bridal Blouses",
    subcategory: "Zardozi Bridal Blouses",
    fabric: "Heritage Raw Silk",
    occasion: "Wedding",
    neckline: "Broad Sweetheart",
    sleeve: "Elbow Sleeve",
    color: "Crimson Red",
    workType: "Peacock & Elephant Bullion Zardozi with Pearl Fringe",
    padding: "Built-in Luxury Cups",
    closure: "Back Hook & Tie-up Latkans",
    margin: "2 inches on both sides",
  },
  {
    id: "p5",
    brand: "Tarun Tahiliani",
    title: "Crimson Zardozi Plunging V-Neck Bridal Blouse",
    price: 5499,
    mrp: 8999,
    rating: 4.8,
    reviews: 980,
    image: img("wedding_blouse_crimson_deep_v.png"),
    images: [
      img("wedding_blouse_crimson_deep_v.png"),
      img("wedding_blouse_crimson_floral.png"),
      img("wedding_blouse_pink_lattice.png"),
    ],
    tag: "BRIDAL",
    category: "Bridal Blouses",
    subcategory: "Brocade Blouses",
    fabric: "Silk Velvet & Raw Silk",
    occasion: "Wedding",
    neckline: "Plunging V-Neck",
    sleeve: "Short Sleeve with Bead Tassels",
    color: "Crimson Red",
    workType: "Intricate Antique Gold Zardozi & Hanging Red Bead Fringe",
    padding: "Built-in Luxury Cups",
    closure: "Concealed Side Zipper",
    margin: "2 inches on both sides",
  },
  {
    id: "p8",
    brand: "Raw Mango",
    title: "Royal Velvet Maroon Mango Zari Bridal Blouse",
    price: 5999,
    mrp: 9499,
    rating: 4.9,
    reviews: 640,
    image: img("bridal_blouse_maroon_velvet.png"),
    images: [
      img("bridal_blouse_maroon_velvet.png"),
      img("bridal_blouse_crimson_peacock.png"),
      img("bridal_blouse_purple_banarasi.png"),
    ],
    tag: "RECEPTION",
    category: "Bridal Blouses",
    subcategory: "Velvet Bridal Blouses",
    fabric: "Royal Micro Velvet",
    occasion: "Reception",
    neckline: "Sweetheart",
    sleeve: "Elbow Sleeve",
    color: "Maroon",
    workType: "Intricate Paisley Sleeve Motifs & Floral Zari Borders",
    padding: "Built-in Luxury Cups",
    closure: "Back Hook & Eye",
    margin: "2 inches on both sides",
  },
  {
    id: "p9",
    brand: "Manish Malhotra",
    title: "Ruby Rose Geometric Lattice Zardozi Bridal Blouse",
    price: 4899,
    mrp: 7999,
    rating: 4.8,
    reviews: 512,
    image: img("wedding_blouse_pink_lattice.png"),
    images: [
      img("wedding_blouse_pink_lattice.png"),
      img("wedding_blouse_crimson_deep_v.png"),
      img("wedding_blouse_burgundy_sheer.png"),
    ],
    tag: "BRIDAL",
    category: "Bridal Blouses",
    subcategory: "Hand-Embroidered Blouses",
    fabric: "Pure Silk",
    occasion: "Wedding",
    neckline: "Scalloped Sweetheart",
    sleeve: "Elbow Sleeve with Diamond Zardozi Lattice",
    color: "Ruby Pink",
    workType: "Geometric Jali Gridwork, Pearl Accents & Zari Embroidery",
    padding: "Built-in Luxury Cups",
    closure: "Back Hook & Eye",
    margin: "2 inches on both sides",
  },
  {
    id: "p10",
    brand: "Anita Dongre",
    title: "Crimson Floral Resham Embroidered Bridal Blouse",
    price: 4299,
    mrp: 6999,
    rating: 4.7,
    reviews: 430,
    image: img("wedding_blouse_crimson_floral.png"),
    images: [
      img("wedding_blouse_crimson_floral.png"),
      img("wedding_blouse_crimson_zardozi.png"),
      img("wedding_blouse_pink_lattice.png"),
    ],
    tag: "BRIDAL",
    category: "Bridal Blouses",
    subcategory: "Zari Woven Blouses",
    fabric: "Raw Silk",
    occasion: "Wedding",
    neckline: "Sweetheart V-Neck",
    sleeve: "Elbow Sleeve",
    color: "Crimson Red",
    workType: "All-Over Floral Resham Threadwork & Delicate Gold Foil",
    padding: "Built-in Luxury Cups",
    closure: "Side Concealed Zipper",
    margin: "2 inches on both sides",
  },
  {
    id: "p11",
    brand: "Ritu Kumar",
    title: "Royal Crimson Heritage Zardozi Bridal Blouse",
    price: 4799,
    mrp: 7499,
    rating: 4.8,
    reviews: 380,
    image: img("wedding_blouse_crimson_zardozi.png"),
    images: [
      img("wedding_blouse_crimson_zardozi.png"),
      img("wedding_blouse_burgundy_sheer.png"),
      img("wedding_blouse_crimson_deep_v.png"),
    ],
    tag: "HERITAGE BRIDAL",
    category: "Bridal Blouses",
    subcategory: "Temple Border Blouses",
    fabric: "Heritage Raw Silk",
    occasion: "Wedding",
    neckline: "Deep V-Neck",
    sleeve: "Elbow Sleeve",
    color: "Crimson Red",
    workType: "Heritage Aari & Zardozi Boota with Contrast Embroidered Cuff",
    padding: "Built-in Luxury Cups",
    closure: "Back Hook & Eye",
    margin: "2 inches on both sides",
  },
  {
    id: "p20",
    brand: "Torani",
    title: "Torani Burgundy Sheer Sleeve Velvet Bridal Blouse",
    price: 5899,
    mrp: 9499,
    rating: 4.9,
    reviews: 310,
    image: img("wedding_blouse_burgundy_sheer.png"),
    images: [
      img("wedding_blouse_burgundy_sheer.png"),
      img("wedding_blouse_crimson_zardozi.png"),
      img("wedding_blouse_crimson_floral.png"),
    ],
    tag: "BRIDAL COUTURE",
    category: "Bridal Blouses",
    subcategory: "Custom Fit Blouses",
    fabric: "Royal Velvet & Sheer Organza",
    occasion: "Wedding",
    neckline: "Sweetheart Illusion",
    sleeve: "Full Sheer Embroidered Sleeve",
    color: "Burgundy Maroon",
    workType: "Velvet Bustier with Sheer Organza Resham & Aari Sleeve Embroidery",
    padding: "Built-in Luxury Cups",
    closure: "Back Concealed Hook & Eye",
    margin: "2 inches on both sides",
  },
  {
    id: "p12",
    brand: "Tarun Tahiliani",
    title: "Emerald Velvet Inverted V-Back Bridal Blouse",
    price: 5799,
    mrp: 9299,
    rating: 4.9,
    reviews: 410,
    image: img("bridal_blouse_emerald_back.png"),
    images: [
      img("bridal_blouse_emerald_back.png"),
      img("bridal_blouse_pastel_couture.png"),
      img("bridal_blouse_maroon_velvet.png"),
    ],
    tag: "DESIGNER STATEMENT",
    category: "Bridal Blouses",
    subcategory: "Backless Designer Blouses",
    fabric: "Royal Velvet",
    occasion: "Reception",
    neckline: "Deep Inverted V-Back",
    sleeve: "Elbow Sleeve",
    color: "Emerald Green",
    workType: "Floral Zardozi Lattice & Emerald Bead Latkans",
    padding: "Built-in Luxury Cups",
    closure: "Concealed Side Zipper & Back Dori",
    margin: "2 inches on both sides",
  },
  {
    id: "p18",
    brand: "Anita Dongre",
    title: "Pastel Illusion Back Zardozi Bridal Couture Blouse",
    price: 6499,
    mrp: 10499,
    rating: 4.9,
    reviews: 320,
    image: img("bridal_blouse_pastel_couture.png"),
    images: [
      img("bridal_blouse_pastel_couture.png"),
      img("bridal_blouse_emerald_back.png"),
      img("bridal_blouse_purple_banarasi.png"),
    ],
    tag: "COUTURE ILLUSION",
    category: "Bridal Blouses",
    subcategory: "Hand-Embroidered Blouses",
    fabric: "Silk & Sheer Illusion Net",
    occasion: "Wedding",
    neckline: "Cutwork Illusion Back",
    sleeve: "Elbow Sleeve with Pearl Tassels",
    color: "Pastel Turquoise",
    workType: "3D Bullion Zardozi, Tree of Life & Pearl Cluster Tassels",
    padding: "Built-in Luxury Cups",
    closure: "Back Concealed Hook & Eye",
    margin: "2 inches on both sides",
  },
  {
    id: "p19",
    brand: "Manish Malhotra",
    title: "Royal Purple Banarasi Gemstone Tassel Bridal Blouse",
    price: 6799,
    mrp: 10999,
    rating: 4.8,
    reviews: 290,
    image: img("bridal_blouse_purple_banarasi.png"),
    images: [
      img("bridal_blouse_purple_banarasi.png"),
      img("bridal_blouse_pastel_couture.png"),
      img("bridal_blouse_crimson_peacock.png"),
    ],
    tag: "ROYAL BANARASI",
    category: "Bridal Blouses",
    subcategory: "Custom Fit Blouses",
    fabric: "Banarasi Brocade Silk",
    occasion: "Wedding",
    neckline: "Temple U-Neck",
    sleeve: "Geometric Cutwork Sleeve with Amethyst Tassels",
    color: "Royal Purple",
    workType: "Fine Zari Bootis, Crystal Beading & Cascading Gemstone Chains",
    padding: "Built-in Luxury Cups",
    closure: "Back Hook & Tie-up Latkans",
    margin: "2 inches on both sides",
  },
  {
    id: "p2",
    brand: "Sabyasachi",
    title: "Royal Crimson Zardozi Heritage Bridal Lehenga",
    price: 29999,
    mrp: 45999,
    rating: 4.9,
    reviews: 842,
    image: img("lehenga_crimson_royal_bridal.png"),
    images: [img("lehenga_crimson_royal_bridal.png"), img("lehenga_ruby_rose_embroidered.png")],
    tag: "BRIDAL COUTURE",
    fabric: "Heritage Raw Silk & Velvet",
    occasion: "Wedding",
    category: "Lehengas",
    subcategory: "Bridal Lehengas",
    color: "Crimson Red",
  },
  {
    id: "p24",
    brand: "Manish Malhotra",
    title: "Ruby Rose Sequin Embroidered Wedding Lehenga",
    price: 26999,
    mrp: 39999,
    rating: 4.8,
    reviews: 620,
    image: img("lehenga_ruby_rose_embroidered.png"),
    images: [img("lehenga_ruby_rose_embroidered.png"), img("lehenga_crimson_royal_bridal.png")],
    tag: "WEDDING",
    fabric: "Silk Georgette & Organza",
    occasion: "Wedding",
    category: "Lehengas",
    subcategory: "Wedding Lehengas",
    color: "Ruby Pink",
  },
  {
    id: "p13",
    brand: "Ritu Kumar",
    title: "Beige & Dusty Pink Printed Straight-Cut Salwar Suit",
    price: 5499,
    mrp: 8999,
    rating: 4.8,
    reviews: 310,
    image: img("salwar_suit_beige_pink_printed.png"),
    images: [
      img("salwar_suit_beige_pink_printed.png"),
      img("salwar_suit_rose_patiala_embroidered.png"),
    ],
    tag: "SIGNATURE",
    fabric: "Pure Chanderi Silk",
    occasion: "Festive Wear",
    category: "Salwar Suits",
    subcategory: "Straight-Cut Suits",
    color: "Beige & Pink",
  },
  {
    id: "p14",
    brand: "Anita Dongre",
    title: "Dusty Rose Embellished Patiala Salwar Suit Set",
    price: 6999,
    mrp: 10999,
    rating: 4.9,
    reviews: 240,
    image: img("salwar_suit_rose_patiala_embroidered.png"),
    images: [
      img("salwar_suit_rose_patiala_embroidered.png"),
      img("salwar_suit_beige_pink_printed.png"),
    ],
    tag: "FESTIVE COUTURE",
    fabric: "Silk Georgette & Organza",
    occasion: "Festive Wear",
    category: "Salwar Suits",
    subcategory: "Designer Salwar Suits",
    color: "Dusty Rose Pink",
  },
  {
    id: "p15",
    brand: "Tarun Tahiliani",
    title: "Terracotta Belted Peplum & Tailored Trouser Ensemble",
    price: 12999,
    mrp: 18999,
    rating: 4.9,
    reviews: 180,
    image: img("indo_western_rust_peplum_set.png"),
    images: [img("indo_western_rust_peplum_set.png"), img("indo_western_ivory_jacket_set.png")],
    tag: "RUNWAY",
    fabric: "Textured Raw Silk & Khadi",
    occasion: "Reception",
    category: "Indo-Western",
    subcategory: "Fusion Outfits",
    color: "Terracotta Rust & Ivory",
  },
  {
    id: "p16",
    brand: "Manish Malhotra",
    title: "Ivory Crop Jacket & Flare Pant Indo-Western Set",
    price: 14999,
    mrp: 21999,
    rating: 4.8,
    reviews: 145,
    image: img("indo_western_ivory_jacket_set.png"),
    images: [img("indo_western_ivory_jacket_set.png"), img("indo_western_rust_peplum_set.png")],
    tag: "DESIGNER STATEMENT",
    fabric: "Handloom Linen & Silk",
    occasion: "Sangeet",
    category: "Indo-Western",
    subcategory: "Pre-Draped Ensembles",
    color: "Ivory & Turquoise",
  },
  {
    id: "p17",
    brand: "Raw Mango",
    title: "Royal Plum Zari Embroidered Silk Festive Ensemble",
    price: 14999,
    mrp: 21999,
    rating: 4.9,
    reviews: 420,
    image: img("festive_wear_plum_zari_silk.png"),
    images: [img("festive_wear_plum_zari_silk.png"), img("festive_wear_teal_velvet_shawl.png")],
    tag: "FESTIVE SPECIAL",
    fabric: "Raw Silk & Banarasi Tissue",
    occasion: "Festive Wear",
    category: "Festive Wear",
    subcategory: "Celebration Ensembles",
    color: "Royal Plum & Gold",
  },
  {
    id: "p4",
    brand: "Ritu Kumar",
    title: "Peacock Teal Silk Kurta Set with Embroidered Velvet Shawl",
    price: 16999,
    mrp: 24999,
    rating: 4.9,
    reviews: 612,
    image: img("festive_wear_teal_velvet_shawl.png"),
    images: [img("festive_wear_teal_velvet_shawl.png"), img("festive_wear_plum_zari_silk.png")],
    tag: "FESTIVE LUXURY",
    fabric: "Pure Silk & Micro Velvet",
    occasion: "Festive Wear",
    category: "Festive Wear",
    subcategory: "Diwali Special",
    color: "Peacock Teal",
  },
  {
    id: "p25",
    brand: "HOPO Lounge",
    title: "Lace Trim Satin Night Suit",
    price: 3499,
    mrp: 5999,
    rating: 4.9,
    reviews: 320,
    image: img("night_suit_1.jpg"),
    images: [img("night_suit_1.jpg")],
    tag: "LOUNGEWEAR",
    category: "Night Suits",
    subcategory: "Satin Nightwear Sets",
    fabric: "Pure Satin Silk",
    occasion: "Lounge & Sleepwear",
    neckline: "V-Neck with Scalloped Lace",
    sleeve: "Full Sleeve with Lace Trim",
    color: "Dusty Rose Pink",
    closure: "Button-Front & Elastic Waistband",
    margin: "Relaxed Comfort Fit",
  },
  {
    id: "p26",
    brand: "HOPO Lounge",
    title: "Satin Wrap Night Suit",
    price: 3899,
    mrp: 6499,
    rating: 4.8,
    reviews: 210,
    image: img("night_suit_2.jpg"),
    images: [img("night_suit_2.jpg")],
    tag: "LUXURY LOUNGE",
    category: "Night Suits",
    subcategory: "Luxury Silk Pajamas",
    fabric: "Silky Smooth Satin",
    occasion: "Lounge & Sleepwear",
    neckline: "Wrap Kimono Collar with Dark Piping",
    sleeve: "Full Sleeve with Contrast Trim",
    color: "Pearl White & Black Trim",
    closure: "Wrap Belt Tie",
    margin: "Relaxed Comfort Fit",
  },
  {
    id: "p27",
    brand: "HOPO Lounge",
    title: "Classic Navy Night Suit",
    price: 3299,
    mrp: 5499,
    rating: 4.9,
    reviews: 450,
    image: img("night_suit_3.jpg"),
    images: [img("night_suit_3.jpg")],
    tag: "BESTSELLER",
    category: "Night Suits",
    subcategory: "Satin Nightwear Sets",
    fabric: "Premium Navy Satin Silk",
    occasion: "Lounge & Sleepwear",
    neckline: "Notched Collar with White Piping",
    sleeve: "Full Sleeve with Piped Cuffs",
    color: "Midnight Navy Blue",
    closure: "Button-Up Front & Drawstring Waist",
    margin: "Relaxed Comfort Fit",
  },
  {
    id: "p28",
    brand: "HOPO Lounge",
    title: "Striped Cotton Night Suit",
    price: 2499,
    mrp: 3999,
    rating: 4.7,
    reviews: 180,
    image: img("night_suit_4.jpg"),
    images: [img("night_suit_4.jpg")],
    tag: "BREATHABLE COTTON",
    category: "Night Suits",
    subcategory: "Cotton Lounge Sets",
    fabric: "100% Breathable Striped Cotton",
    occasion: "Lounge & Sleepwear",
    neckline: "Spread Collar with Ruffled Trim",
    sleeve: "Full Sleeve with Ruffled Flounce Cuffs",
    color: "Blush Pink & White Stripe",
    closure: "Front Button Placket",
    margin: "Relaxed Breathable Fit",
  },
  {
    id: "p29",
    brand: "HOPO Lounge",
    title: "Satin Night Suit",
    price: 3699,
    mrp: 5999,
    rating: 4.8,
    reviews: 290,
    image: img("night_suit_5.jpg"),
    images: [img("night_suit_5.jpg")],
    tag: "ROYAL LOUNGE",
    category: "Night Suits",
    subcategory: "Satin Nightwear Sets",
    fabric: "Deep Lustrous Satin",
    occasion: "Lounge & Sleepwear",
    neckline: "Classic Notch Lapel",
    sleeve: "Full Sleeve with Deep Hem",
    color: "Deep Crimson Red",
    closure: "Single-Breasted Button Placket",
    margin: "Relaxed Comfort Fit",
  },
  {
    id: "p31",
    brand: "HOPO Lounge",
    title: "Premium Korean Berry Cotton Night Suit",
    price: 2999,
    mrp: 4999,
    rating: 4.9,
    reviews: 210,
    image: img("night_suit_6.jpg"),
    images: [img("night_suit_6.jpg")],
    tag: "KOREAN EDIT",
    category: "Night Suits",
    subcategory: "Cotton Lounge Sets",
    fabric: "Premium Cotton Berry Crush",
    occasion: "Lounge & Sleepwear",
    neckline: "Notch Lapel with Piping",
    sleeve: "Short Sleeve with Piped Hem",
    color: "Berry Cream",
    closure: "Button Placket & Elastic Waist",
    margin: "Relaxed Comfort Fit",
  },
  {
    id: "p32",
    brand: "HOPO Lounge",
    title: "Fancy Korean Sky Blue Floral Night Suit",
    price: 3299,
    mrp: 5499,
    rating: 4.8,
    reviews: 195,
    image: img("night_suit_7.jpg"),
    images: [img("night_suit_7.jpg")],
    tag: "NEW LAUNCH",
    category: "Night Suits",
    subcategory: "Cotton Lounge Sets",
    fabric: "Breathable Soft Cotton",
    occasion: "Lounge & Sleepwear",
    neckline: "Square Lace Neck with Ribbon Bow",
    sleeve: "Short Sleeve",
    color: "Sky Blue Floral",
    closure: "Pull-On Top & Elastic Waist Pants",
    margin: "Relaxed Comfort Fit",
  },
  {
    id: "p33",
    brand: "HOPO Lounge",
    title: "Fancy Korean Soft Peach Floral Night Suit",
    price: 3299,
    mrp: 5499,
    rating: 4.9,
    reviews: 160,
    image: img("night_suit_8.jpg"),
    images: [img("night_suit_8.jpg")],
    tag: "TRENDING",
    category: "Night Suits",
    subcategory: "Cotton Lounge Sets",
    fabric: "Breathable Soft Cotton",
    occasion: "Lounge & Sleepwear",
    neckline: "Square Lace Neck with Ribbon Bow",
    sleeve: "Short Sleeve",
    color: "Soft Peach Floral",
    closure: "Pull-On Top & Elastic Waist Pants",
    margin: "Relaxed Comfort Fit",
  },
  {
    id: "p34",
    brand: "HOPO Lounge",
    title: "Premium Korean Striped Floral Night Suit",
    price: 2999,
    mrp: 4999,
    rating: 4.8,
    reviews: 145,
    image: img("night_suit_9.jpg"),
    images: [img("night_suit_9.jpg")],
    tag: "KOREAN EDIT",
    category: "Night Suits",
    subcategory: "Cotton Lounge Sets",
    fabric: "Premium Cotton Crush",
    occasion: "Lounge & Sleepwear",
    neckline: "Spread Collar with Pink Piping",
    sleeve: "Short Sleeve",
    color: "Mint & White Stripe",
    closure: "Front Button Placket & Elastic Shorts",
    margin: "Relaxed Comfort Fit",
  },
  {
    id: "p35",
    brand: "HOPO Lounge",
    title: "Korean Peach Ruffle Cotton Night Suit",
    price: 3599,
    mrp: 5999,
    rating: 4.9,
    reviews: 230,
    image: img("night_suit_10.jpg"),
    images: [img("night_suit_10.jpg")],
    tag: "BESTSELLER",
    category: "Night Suits",
    subcategory: "Cotton Lounge Sets",
    fabric: "100% Breathable Cotton",
    occasion: "Lounge & Sleepwear",
    neckline: "Ruffled Collar with Lapel",
    sleeve: "Full Sleeve with Ruffled Cuffs",
    color: "Peach Orange",
    closure: "Button Placket & Elastic Waist Pyjamas",
    margin: "Relaxed Comfort Fit",
  },
];
/**
 * Preserved historical catalog archive.
 * Retains historical product records (e.g. Sarees) so historical customer order tracking,
 * past order receipts, and administrative references resolve safely without appearing
 * in the active customer-facing shopping experience.
 */
export const HISTORICAL_PRODUCTS = [
  {
    id: "p1",
    brand: "Anita Dongre",
    title: "Royal Wine Maroon Zari Banarasi Silk Saree",
    price: 8499,
    mrp: 14999,
    rating: 4.8,
    reviews: 1264,
    image: img("saree_wine_maroon_silk.png"),
    images: [
      img("saree_wine_maroon_silk.png"),
      img("saree_rust_orange_banarasi.png"),
      img("saree_black_silver_zari.png"),
    ],
    tag: "ARCHIVED",
    fabric: "Pure Silk",
    occasion: "Wedding",
    category: "Sarees",
    subcategory: "Banarasi Sarees",
    color: "Wine Maroon",
    isArchived: true,
    status: "archived",
  },
  {
    id: "p6",
    brand: "Manish Malhotra",
    title: "Royal Rust Gold Banarasi Katan Silk Saree",
    price: 18999,
    mrp: 28999,
    rating: 4.9,
    reviews: 618,
    image: img("saree_rust_orange_banarasi.png"),
    images: [
      img("saree_rust_orange_banarasi.png"),
      img("saree_metallic_copper_tissue.png"),
      img("saree_ivory_embroidered_organza.png"),
    ],
    tag: "ARCHIVED",
    occasion: "Wedding",
    category: "Sarees",
    subcategory: "Banarasi Sarees",
    color: "Rust Gold",
    fabric: "Katan Silk",
    isArchived: true,
    status: "archived",
  },
  {
    id: "p21",
    brand: "Sabyasachi",
    title: "Midnight Black Silver Zari Chanderi Saree",
    price: 14999,
    mrp: 22999,
    rating: 4.9,
    reviews: 480,
    image: img("saree_black_silver_zari.png"),
    images: [
      img("saree_black_silver_zari.png"),
      img("saree_metallic_copper_tissue.png"),
      img("saree_wine_maroon_silk.png"),
    ],
    tag: "ARCHIVED",
    fabric: "Chanderi Silk",
    occasion: "Party Wear",
    category: "Sarees",
    subcategory: "Handloom Sarees",
    color: "Midnight Black",
    isArchived: true,
    status: "archived",
  },
  {
    id: "p22",
    brand: "Tarun Tahiliani",
    title: "Metallic Copper Crushed Tissue Silk Saree",
    price: 16499,
    mrp: 24999,
    rating: 4.8,
    reviews: 390,
    image: img("saree_metallic_copper_tissue.png"),
    images: [
      img("saree_metallic_copper_tissue.png"),
      img("saree_black_silver_zari.png"),
      img("saree_rust_orange_banarasi.png"),
    ],
    tag: "ARCHIVED",
    fabric: "Tissue Silk",
    occasion: "Reception",
    category: "Sarees",
    subcategory: "Party Wear Sarees",
    color: "Metallic Copper",
    isArchived: true,
    status: "archived",
  },
  {
    id: "p23",
    brand: "Raw Mango",
    title: "Handcrafted Ivory Embroidered Organza Saree",
    price: 21999,
    mrp: 32999,
    rating: 4.9,
    reviews: 275,
    image: img("saree_ivory_embroidered_organza.png"),
    images: [
      img("saree_ivory_embroidered_organza.png"),
      img("saree_rust_orange_banarasi.png"),
      img("saree_wine_maroon_silk.png"),
    ],
    tag: "ARCHIVED",
    fabric: "Organza Silk",
    occasion: "Wedding",
    category: "Sarees",
    subcategory: "Organza Sarees",
    color: "Ivory Cream",
    isArchived: true,
    status: "archived",
  },
];
export const COMPLETE_THE_LOOK = [
  {
    id: "a1",
    brand: "Amrapali",
    title: "Gold polki jhumka earrings",
    price: 3499,
    mrp: 4999,
    rating: 4.7,
    reviews: 220,
    image: img("gold_polki_jhumkas.png"),
  },
  {
    id: "a2",
    brand: "Hidesign",
    title: "Maroon embroidered potli",
    price: 1899,
    mrp: 2799,
    rating: 4.5,
    reviews: 142,
    image: img("maroon_potli.png"),
  },
  {
    id: "a3",
    brand: "Inc.5",
    title: "Gold block heel juttis",
    price: 2299,
    mrp: 3299,
    rating: 4.4,
    reviews: 311,
    image: img("gold_block_heel_juttis.png"),
  },
  {
    id: "a4",
    brand: "Tribe Amrapali",
    title: "Temple necklace set",
    price: 4499,
    mrp: 6499,
    rating: 4.6,
    reviews: 98,
    image: img("temple_necklace_set.png"),
  },
];
export const DISCOVER_FEED = [
  {
    id: "d1",
    kind: "Styling Tip",
    title: "How to style a sweetheart neck zardozi bridal blouse",
    image: img("wedding_blouse_crimson_deep_v.png"),
    height: 320,
  },
  {
    id: "d2",
    kind: "Inspiration",
    title: "Top 10 bridal & wedding blouses this season",
    image: img("bridal_blouse_crimson_peacock.png"),
    height: 420,
  },
  {
    id: "d3",
    kind: "Trending Combo",
    title: "Raw silk bridal blouse with heirloom zardozi — a royal classic",
    image: img("wedding_blouse_crimson_floral.png"),
    height: 280,
  },
  {
    id: "d4",
    kind: "Influencer Look",
    title: "Diana's gold-on-maroon wedding style",
    image: img("bridal_blouse_maroon_velvet.png"),
    height: 380,
  },
  {
    id: "d5",
    kind: "Styling Tip",
    title: "5 ways to style wedding blouses for grand celebrations",
    image: img("wedding_blouse_pink_lattice.png"),
    height: 320,
  },
  {
    id: "d6",
    kind: "Inspiration",
    title: "Floral prints and sweetheart neck blouses for wedding getaways",
    image: img("wedding_blouse_crimson_floral.png"),
    height: 360,
  },
  {
    id: "d7",
    kind: "Influencer Look",
    title: "Handcrafted zardozi blouse — Aanya's wedding reception pick",
    image: img("wedding_blouse_crimson_zardozi.png"),
    height: 300,
  },
  {
    id: "d8",
    kind: "Trending Combo",
    title: "Emerald statement back for the grand wedding",
    image: img("bridal_blouse_emerald_back.png"),
    height: 400,
  },
];
export const REVIEWS = [
  {
    id: "r1",
    name: "Priya S.",
    rating: 5,
    verified: true,
    helpful: 84,
    text: "Absolutely gorgeous! The craftsmanship and zardozi detailing are stunning, and the fit is tailored to perfection. Wore it for my wedding.",
    image: img("wedding_blouse_crimson_deep_v.png"),
    date: "12 Apr 2026",
  },
  {
    id: "r2",
    name: "Aanya R.",
    rating: 4,
    verified: true,
    helpful: 41,
    text: "Lovely quality and quick delivery. The blouse fitting is fantastic and the zardozi detail is stunning.",
    image: img("bridal_blouse_crimson_peacock.png"),
    date: "03 Apr 2026",
  },
  {
    id: "r3",
    name: "Meera K.",
    rating: 5,
    verified: true,
    helpful: 122,
    text: "Got so many compliments. The zari work is fine and the blouse fabric is generous.",
    image: img("wedding_blouse_pink_lattice.png"),
    date: "28 Mar 2026",
  },
  {
    id: "r4",
    name: "Sneha T.",
    rating: 4,
    verified: false,
    helpful: 17,
    text: "Beautiful wedding blouse with exquisite embroidery. Colour is a deeper maroon in person, which I actually loved.",
    image: img("bridal_blouse_maroon_velvet.png"),
    date: "22 Mar 2026",
  },
];
export const OFFERS = [
  {
    id: "o1",
    title: "FESTIVE40",
    desc: "Flat 40% off on Festive",
    min: "Min ₹2999",
    color: "royal",
  },
  {
    id: "o2",
    title: "WEDDING25",
    desc: "Extra 25% off on Bridal & Wedding Blouses",
    min: "Min ₹4999",
    color: "gold",
  },
  {
    id: "o3",
    title: "ICICI10",
    desc: "10% instant discount on ICICI Bank cards",
    min: "Min ₹1500",
    color: "soft",
  },
  {
    id: "o4",
    title: "FIRST500",
    desc: "₹500 off on your first order",
    min: "Min ₹1999",
    color: "soft",
  },
];
export const ASSISTANT_SCRIPT = [
  { role: "user", text: "I need an outfit for a wedding under ₹15000." },
  {
    role: "assistant",
    text: "Lovely — here are curated looks that work beautifully for grand weddings. Each set pairs a luxury lehenga or ensemble with a matching bridal blouse and jewelry.",
    looks: ["p3", "p9", "p5", "p2"],
  },
  { role: "user", text: "Show me bridal blouses." },
  {
    role: "assistant",
    text: "Our bridal blouse collection features hand-embroidered zardozi, raw silk fabrics, and gold brocades crafted for special occasions.",
    looks: ["p3", "p5", "p8"],
  },
];
export const findProduct = (id) =>
  [...PRODUCTS, ...HISTORICAL_PRODUCTS, ...COMPLETE_THE_LOOK].find((p) => p.id === id) ??
  PRODUCTS[0];
