export const HOPO_IMAGE_REGISTRY = [
  {
    filename: "hopo_logo.png",
    category: "Branding",
    usageLocation: "Navbar, Footer, Brand Emblems",
    source: "HOPO SHOP Original",
    sourceUrl: "Internal Brand Asset",
    photographer: "HOPO SHOP Atelier",
    license: "Proprietary",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics: "Official brand trademark logotype",
  },
  {
    filename: "saree_rust_orange_banarasi.png",
    category: "Sarees",
    usageLocation:
      "Homepage Hero Arch, Hero Slider, Sarees Category Tile, Product p6, Product p1 Gallery",
    source: "User-Provided Authentic Saree Haute Couture Photography",
    sourceUrl: "Local Archive (/images/saree_rust_orange_banarasi.png)",
    photographer: "Heritage Royal Palace Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Royal rust gold/terracotta Banarasi Katan silk saree with all-over heavy gold zari floral jaal and broad pallu, styled in palace arch",
  },
  {
    filename: "saree_wine_maroon_silk.png",
    category: "Sarees",
    usageLocation:
      "Product p1, Best Sellers, Fabrics (Pure Silk), Discover Feed, Customer Reviews, About Brand",
    source: "User-Provided Authentic Saree Haute Couture Photography",
    sourceUrl: "Local Archive (/images/saree_wine_maroon_silk.png)",
    photographer: "Bespoke Silk Weavers Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Deep royal wine maroon Banarasi pure silk saree with shimmering gold zari vine weaves, broad floral border, and traditional jewelry",
  },
  {
    filename: "saree_black_silver_zari.png",
    category: "Sarees",
    usageLocation: "Product p21 (Midnight Black Silver Zari Chanderi Saree), Product Galleries",
    source: "User-Provided Authentic Saree Haute Couture Photography",
    sourceUrl: "Local Archive (/images/saree_black_silver_zari.png)",
    photographer: "Modern Heritage Studio",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Midnight black lightweight Chanderi/organza saree with exquisite silver metallic zari floral border and buttis, silver choker styling",
  },
  {
    filename: "saree_metallic_copper_tissue.png",
    category: "Sarees",
    usageLocation: "Product p22 (Metallic Copper Crushed Tissue Silk Saree), Product Galleries",
    source: "User-Provided Authentic Saree Haute Couture Photography",
    sourceUrl: "Local Archive (/images/saree_metallic_copper_tissue.png)",
    photographer: "Runway Atelier Studio",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Metallic copper rust crushed tissue silk saree with shimmering sequin/zari border and deep sweetheart neckline blouse",
  },
  {
    filename: "saree_ivory_embroidered_organza.png",
    category: "Sarees",
    usageLocation: "Product p23 (Handcrafted Ivory Embroidered Organza Saree), Product Galleries",
    source: "User-Provided Authentic Saree Haute Couture Photography",
    sourceUrl: "Local Archive (/images/saree_ivory_embroidered_organza.png)",
    photographer: "Bespoke Couture Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Handcrafted ivory cream organza tissue saree with delicate pastel floral embroidery, paired with a maroon floral embroidered blouse",
  },
  {
    filename: "bridal_blouse_crimson_peacock.png",
    category: "Bridal Blouses",
    usageLocation:
      "Product p3, Bridal Blouses Category Card, Homepage Bento, Occasion Wedding, Best Sellers, Lookbook, Instagram, Trends",
    source: "User-Provided Authentic Bridal Blouse Haute Couture Photography",
    sourceUrl: "Local Archive (/images/bridal_blouse_crimson_peacock.png)",
    photographer: "Bespoke Bridal Couture Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Royal crimson raw silk bridal blouse, heavily encrusted with gold bullion zardozi, peacock and elephant motifs, ruby/emerald inlays, and dainty pearl fringe tassels at the waist hem",
  },
  {
    filename: "wedding_blouse_crimson_deep_v.png",
    category: "Wedding Blouses",
    usageLocation:
      "Product p5, Homepage Bento Card 2, Best Sellers, Lookbook, Instagram, Trends, Category Tile, Discover, Reviews",
    source: "User-Provided Authentic Wedding Blouse Haute Couture Photography",
    sourceUrl: "Local Archive (/images/wedding_blouse_crimson_deep_v.png)",
    photographer: "Bespoke Bridal Couture Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Royal crimson silk choli featuring deep plunging V-neckline, heavy antique gold bullion zardozi, red bead droplet hem, emerald-polki choker styling",
  },
  {
    filename: "bridal_blouse_maroon_velvet.png",
    category: "Bridal Blouses",
    usageLocation: "Product p8, Occasion Reception, Best Sellers, Lookbook, Trends, Reviews",
    source: "User-Provided Authentic Bridal Blouse Haute Couture Photography",
    sourceUrl: "Local Archive (/images/bridal_blouse_maroon_velvet.png)",
    photographer: "Bespoke Bridal Couture Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Deep maroon micro-velvet bridal blouse featuring intricate gold mango/paisley sleeve embroidery, floral sweetheart border, and polki necklace styling",
  },
  {
    filename: "wedding_blouse_pink_lattice.png",
    category: "Wedding Blouses",
    usageLocation: "Product p9, Occasion Sangeet, Discover Feed, Instagram Gallery, Trends",
    source: "User-Provided Authentic Wedding Blouse Haute Couture Photography",
    sourceUrl: "Local Archive (/images/wedding_blouse_pink_lattice.png)",
    photographer: "Heritage Palace Bridal Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Lakeside palace shoot of model in ruby-rose pink blouse with geometric diamond zardozi lattice, scalloped border and pearl choker",
  },
  {
    filename: "wedding_blouse_crimson_floral.png",
    category: "Wedding Blouses",
    usageLocation: "Product p10, Occasion Haldi/Wedding, Discover Feed, Instagram Gallery, Trends",
    source: "User-Provided Authentic Wedding Blouse Haute Couture Photography",
    sourceUrl: "Local Archive (/images/wedding_blouse_crimson_floral.png)",
    photographer: "Bespoke Bridal Couture Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Warm amber studio portrait of model in crimson floral resham embroidered blouse, sweetheart neckline and fine gold thread accents",
  },
  {
    filename: "wedding_blouse_crimson_zardozi.png",
    category: "Wedding Blouses",
    usageLocation: "Product p11, Occasion Mehendi/Wedding, Discover Feed, Instagram Gallery",
    source: "User-Provided Authentic Wedding Blouse Haute Couture Photography",
    sourceUrl: "Local Archive (/images/wedding_blouse_crimson_zardozi.png)",
    photographer: "Heritage Courtyard Bridal Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Heritage palace archway setting with model wearing crimson raw silk V-neck blouse with intricate floral zardozi and traditional bangles",
  },
  {
    filename: "wedding_blouse_burgundy_sheer.png",
    category: "Wedding Blouses",
    usageLocation: "Product p20, Fabric Chanderi/Organza, Instagram Gallery",
    source: "User-Provided Authentic Wedding Blouse Haute Couture Photography",
    sourceUrl: "Local Archive (/images/wedding_blouse_burgundy_sheer.png)",
    photographer: "Torani Couture Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Torani studio couture portrait of model in burgundy velvet bustier blouse with sheer full sleeves and resham floral embroidery",
  },
  {
    filename: "bridal_blouse_emerald_back.png",
    category: "Bridal Blouses",
    usageLocation: "Product p12, Trends (Statement Backless Cuts), Instagram, Discover Feed",
    source: "User-Provided Authentic Bridal Blouse Haute Couture Photography",
    sourceUrl: "Local Archive (/images/bridal_blouse_emerald_back.png)",
    photographer: "Bespoke Bridal Couture Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Royal emerald green velvet bridal blouse with statement plunging inverted V-back cut, heavy floral zardozi lattice, and emerald droplet latkans",
  },
  {
    filename: "bridal_blouse_pastel_couture.png",
    category: "Bridal Blouses",
    usageLocation: "Product p18, Fabrics (Organza Sheer), Discover Feed, Product Detail Galleries",
    source: "User-Provided Authentic Bridal Blouse Haute Couture Photography",
    sourceUrl: "Local Archive (/images/bridal_blouse_pastel_couture.png)",
    photographer: "Bespoke Bridal Couture Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Pastel turquoise illusion sheer net back bridal couture blouse with 3D bullion zardozi, tree of life / peacock embroidery, and pearl cluster tassel finish",
  },
  {
    filename: "lehenga_crimson_royal_bridal.png",
    category: "Lehengas",
    usageLocation:
      "Hero Slider Slide 3, Lehengas Category Tile, Product p2, Homepage AI Style Card, About Brand",
    source: "User-Provided Authentic Lehenga Haute Couture Photography",
    sourceUrl: "Local Archive (/images/lehenga_crimson_royal_bridal.png)",
    photographer: "Bespoke Bridal Couture Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Royal crimson raw silk and velvet bridal lehenga encrusted with antique gold bullion zardozi, temple arch kalis, and scalloped dupatta",
  },
  {
    filename: "lehenga_ruby_rose_embroidered.png",
    category: "Lehengas",
    usageLocation:
      "Product p24 (Ruby Rose Sequin Wedding Lehenga), Onboarding Slide, Product p2 Gallery",
    source: "User-Provided Authentic Lehenga Haute Couture Photography",
    sourceUrl: "Local Archive (/images/lehenga_ruby_rose_embroidered.png)",
    photographer: "Heritage Couture Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Deep ruby rose pink bridal lehenga with radiating peacock feather kali embroidery in golden thread and sequins, scalloped veil dupatta",
  },
  {
    filename: "festive_wear_teal_velvet_shawl.png",
    category: "Festive Wear",
    usageLocation: "Product p4, About Brand (/about-brand), Product p17 Gallery",
    source: "User-Provided Authentic Festive Wear Haute Couture Photography",
    sourceUrl: "Local Archive (/images/festive_wear_teal_velvet_shawl.png)",
    photographer: "Bespoke Royal Festive Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Regal peacock teal silk kurta set with an opulent midnight-teal micro-velvet shawl embroidered with floral threadwork and scalloped border",
  },
  {
    filename: "blouse_lookbook_hero.png",
    category: "Lookbook Editorial",
    usageLocation: "Lookbook Editorial Banner",
    source: "Wikimedia Commons (File:Saree on display at Dilli Haat.JPG)",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Saree_on_display_at_Dilli_Haat.JPG",
    photographer: "Ekabhishek",
    license: "CC BY-SA 3.0",
    commercialUsePermitted: true,
    attributionRequired: true,
    verifiedDate: "2026-09-04",
    characteristics:
      "Artisanal handloom textiles on exhibition display showcasing heritage weave traditions",
  },
  {
    filename: "bridal_blouse_purple_banarasi.png",
    category: "Bridal Blouses",
    usageLocation: "Product p19, Instagram, Product Detail Galleries",
    source: "User-Provided Authentic Bridal Blouse Haute Couture Photography",
    sourceUrl: "Local Archive (/images/bridal_blouse_purple_banarasi.png)",
    photographer: "Bespoke Bridal Couture Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Royal purple Banarasi brocade silk bridal blouse with geometric diamond arm cutout, fine crystal & gold zari embroidery, and cascading purple stone & gold chain tassels",
  },
  {
    filename: "blouse_craft_embroidery_detail.png",
    category: "Craftsmanship / Macro",
    usageLocation: "Product p2 Detail Gallery (Embroidery Closeup)",
    source: "Wikimedia Commons (File:Zardozi work.jpg)",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Zardozi_work.jpg",
    photographer: "Bundleofemotions",
    license: "CC BY-SA 4.0",
    commercialUsePermitted: true,
    attributionRequired: true,
    verifiedDate: "2026-09-04",
    characteristics:
      "Macro photography of gold bullion and zari wire being hand-embroidered by craftsmen",
  },
  {
    filename: "craftsmanship_detail.png",
    category: "Heritage / Artisan",
    usageLocation: "Product Detail Craftsmanship & About Brand",
    source: "Wikimedia Commons (File:A silk saree loom in Kumbakonam, Tamil Nadu.jpg)",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:A_silk_saree_loom_in_Kumbakonam%2C_Tamil_Nadu.jpg",
    photographer: "Matthew T Rader",
    license: "CC BY-SA 4.0",
    commercialUsePermitted: true,
    attributionRequired: true,
    verifiedDate: "2026-09-04",
    characteristics:
      "Documentary photography of traditional Indian wooden handloom workshop weaving silk",
  },
  {
    filename: "gold_polki_jhumkas.png",
    category: "Fine Jewelry",
    usageLocation: "Complete The Look a1 (Gold Polki Jhumkas), Wishlist",
    source: "Wikimedia Commons (File:Bridal gold jewellery in Bangladeshi wedding.jpg)",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Bridal_gold_jewellery_in_Bangladeshi_wedding.jpg",
    photographer: "Syed Sajidul Islam",
    license: "CC BY-SA 4.0",
    commercialUsePermitted: true,
    attributionRequired: true,
    verifiedDate: "2026-09-04",
    characteristics:
      "Macro DSLR capture of authentic 22k gold wedding jhumkas with filigree and pearl accents",
  },
  {
    filename: "gold_jhumkas.png",
    category: "Fine Jewelry",
    usageLocation: "Complete The Look a1 (Gold Jhumkas)",
    source: "Wikimedia Commons (File:Bridal gold jewellery in Bangladeshi wedding.jpg)",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Bridal_gold_jewellery_in_Bangladeshi_wedding.jpg",
    photographer: "Syed Sajidul Islam",
    license: "CC BY-SA 4.0",
    commercialUsePermitted: true,
    attributionRequired: true,
    verifiedDate: "2026-09-04",
    characteristics:
      "Macro DSLR capture of authentic 22k gold wedding jhumkas with filigree and pearl accents",
  },
  {
    filename: "maroon_potli.png",
    category: "Accessories",
    usageLocation: "Complete The Look a2 (Maroon Embroidered Potli)",
    source:
      "Wikimedia Commons (File:Close Shot of the Zardozi (Zardouzi) Embroidery Cushion Covers.jpg)",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Close_Shot_of_the_Zardozi_(Zardouzi)_Embroidery_Cushion_Covers.jpg",
    photographer: "Zarood",
    license: "CC BY-SA 3.0",
    commercialUsePermitted: true,
    attributionRequired: true,
    verifiedDate: "2026-09-04",
    characteristics:
      "Macro photograph of hand-stitched zardozi gold bullion and bead embroidery on crimson velvet",
  },
  {
    filename: "gold_block_heel_juttis.png",
    category: "Bridal Footwear",
    usageLocation: "Complete The Look a3 (Gold Block Heel Juttis)",
    source:
      "Wikimedia Commons (File:Indian mojari, 19th century, red velvet with gold embroidery and sequins - Bata Shoe Museum - DSC00132.JPG)",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Indian_mojari,_19th_century,_red_velvet_with_gold_embroidery_and_sequins_-_Bata_Shoe_Museum_-_DSC00132.JPG",
    photographer: "Daderot",
    license: "CC0 (Public Domain Dedication)",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Museum-grade professional photograph of authentic red velvet mojari jutti with metallic gold zardozi and sequins",
  },
  {
    filename: "temple_necklace_set.png",
    category: "Temple Jewelry",
    usageLocation: "Complete The Look a4 (Temple Necklace Set)",
    source:
      "Wikimedia Commons (File:PXL 20231218 152223456 Victoria and Albert Museum Artefacts 01 ancient South Indian jewelry, possibly from Tamil Nadu, with one type of necklace identified as a traditional marriage necklace.jpg)",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:PXL_20231218_152223456_Victoria_and_Albert_Museum_Artefacts_01_ancient_South_Indian_jewelry,_possibly_from_Tamil_Nadu,_with_one_type_of_necklace_identified_as_a_traditional_marriage_necklace.jpg",
    photographer: "Sourabh.biswas003",
    license: "CC BY-SA 4.0",
    commercialUsePermitted: true,
    attributionRequired: true,
    verifiedDate: "2026-09-04",
    characteristics:
      "High-resolution museum artefact photograph of authentic South Indian gold temple marriage necklace",
  },
  {
    filename: "salwar_suit_rose_patiala_embroidered.png",
    category: "Salwar Suits",
    usageLocation: "Product p14, Salwar Suits Category Tile, Product p13 Gallery",
    source: "User-Provided Authentic Salwar Suit Haute Couture Photography",
    sourceUrl: "Local Archive (/images/salwar_suit_rose_patiala_embroidered.png)",
    photographer: "Bespoke Festive Couture Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Dusty rose pink heavily embroidered Patiala salwar suit with sheer net kurta encrusted with gold zari, mirrorwork, pleated dhoti salwar and scalloped veil",
  },
  {
    filename: "salwar_suit_beige_pink_printed.png",
    category: "Salwar Suits",
    usageLocation: "Product p13, Product p14 Gallery",
    source: "User-Provided Authentic Salwar Suit Haute Couture Photography",
    sourceUrl: "Local Archive (/images/salwar_suit_beige_pink_printed.png)",
    photographer: "Modern Heritage Studio",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Refined beige and dusty pink printed straight-cut Chanderi silk salwar suit with matching trousers and ornate printed dupatta",
  },
  {
    filename: "indo_western_rust_peplum_set.png",
    category: "Indo-Western",
    usageLocation: "Product p15, Indo-Western Category Tile, Product p16 Gallery",
    source: "User-Provided Authentic Indo-Western Haute Couture Photography",
    sourceUrl: "Local Archive (/images/indo_western_rust_peplum_set.png)",
    photographer: "Contemporary Heritage Runway Studio",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Terracotta rust belted peplum top with geometric tribal embroidered borders, paired with cream tailored wide-leg trousers",
  },
  {
    filename: "indo_western_ivory_jacket_set.png",
    category: "Indo-Western",
    usageLocation: "Product p16, Product p15 Gallery",
    source: "User-Provided Authentic Indo-Western Haute Couture Photography",
    sourceUrl: "Local Archive (/images/indo_western_ivory_jacket_set.png)",
    photographer: "Modern Couture Runway Atelier",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Ivory textured raw silk jumpsuit with cropped turquoise and copper ikat embroidered jacket, bustier, and wide-leg flare trousers",
  },
  {
    filename: "festive_wear_plum_zari_silk.png",
    category: "Festive Wear",
    usageLocation:
      "Product p17, Festive Wear Category Tile, Occasion Festive Wear, Homepage New Arrivals Card",
    source: "User-Provided Authentic Festive Wear Haute Couture Photography",
    sourceUrl: "Local Archive (/images/festive_wear_plum_zari_silk.png)",
    photographer: "Heritage Royal Festive Studio",
    license: "Proprietary Commercial Rights / User-Provided Source of Truth",
    commercialUsePermitted: true,
    attributionRequired: false,
    verifiedDate: "2026-09-04",
    characteristics:
      "Royal magenta/plum raw silk festive ensemble with antique gold zardozi neckline and sleeve cuffs, gold tissue Banarasi dupatta",
  },
];
